"""Compose a PR description from build logs, test results, and agent records."""

import argparse
import json
import os
import subprocess
from pathlib import Path


def _collect_build_logs() -> str:
    """Collect build logs from /tmp and format as markdown."""
    sections = []
    for log_file in sorted(Path("/tmp").glob("build-*.log")):
        arch = log_file.name.replace("build-", "").replace(".log", "")
        content = log_file.read_text()
        sections.append(f"<details>\n<summary>{arch} build log</summary>\n\n```\n{content[-3000:]}\n```\n</details>")
    return "\n\n".join(sections)


def _collect_test_results() -> str:
    """Collect JUnit XML test results."""
    sections = []
    for junit_file in Path.cwd().glob("**/results/**/*.junit.xml"):
        arch = junit_file.stem
        rel = junit_file.relative_to(Path.cwd())
        content = junit_file.read_text()
        sections.append(f"<details>\n<summary>{arch}</summary>\n\n```xml\n{content}\n```\n</details>")
    return "\n\n".join(sections) if sections else "_No test results found_"


def _collect_qa_records() -> str:
    """Collect QA review records from agent outputs."""
    sections = []
    for qa_file in Path.cwd().glob("**/ai-result.json"):
        try:
            data = json.loads(qa_file.read_text())
            status = data.get("status", "unknown")
            summary = data.get("summary", "no summary")
            sections.append(f"| QA ({qa_file.parent.name}) | {status} | {summary} |")
        except (json.JSONDecodeError, KeyError):
            pass
    if sections:
        header = "| Role | Result |\n|------|--------|\n"
        return "\n".join(["### Adversarial Review Records", header] + sections)
    return ""


def _get_changed_files() -> str:
    """Get list of changed files."""
    result = subprocess.run(
        ["git", "diff", "--name-status", "origin/main...HEAD"],
        capture_output=True, text=True,
    )
    return result.stdout.strip()


def compose_pr_body(scenario: str, oe_version: str = "") -> str:
    """Compose the full PR body."""
    app_name = os.environ.get("PACKAGE", os.environ.get("APP", ""))
    app_version = os.environ.get("APP_VERSION", "")
    os_version = os.environ.get("OS_VERSION", oe_version)

    parts = [
        f"## Automated PR: {app_name} {app_version} on {os_version}",
        "",
        "### Changes",
        "```",
        _get_changed_files(),
        "```",
        "",
        "### Build Proof",
        _collect_build_logs(),
        "",
        "### Test Results",
        _collect_test_results(),
        "",
        _collect_qa_records(),
        "",
        "### Generated By",
        f"- Scenario: {scenario}",
        f"- Image Creator + Image QA (adversarial pair)",
        f"- Testcase Creator + Testcase QA (adversarial pair)",
    ]

    body = "\n".join(parts)
    Path("/tmp/pr-body.md").write_text(body)
    return body


def compose_pr_title(scenario: str) -> str:
    """Compose the PR title."""
    app_name = os.environ.get("PACKAGE", os.environ.get("APP", ""))
    app_version = os.environ.get("APP_VERSION", "")
    os_version = os.environ.get("OS_VERSION", "")

    if scenario == "new-image":
        title = f"[new-image] Add {app_name} {app_version} on {os_version}"
    elif scenario == "version-update":
        title = f"[version-update] {app_name} {app_version} on {os_version}"
    elif scenario == "oe-upgrade":
        title = f"[oe-upgrade] Batch upgrade to openEuler {os_version}"
    else:
        title = f"[auto] {app_name} {app_version} on {os_version}"

    Path("/tmp/pr-title").write_text(title)
    return title


def main() -> None:
    parser = argparse.ArgumentParser(description="Compose PR description")
    parser.add_argument("--scenario", choices=["new-image", "version-update", "oe-upgrade"], required=True)
    parser.add_argument("--oe-version", default="")
    args = parser.parse_args()

    title = compose_pr_title(args.scenario)
    body = compose_pr_body(args.scenario, args.oe_version)

    print(f"PR title: {title}")
    print(f"PR body written to /tmp/pr-body.md ({len(body)} chars)")


if __name__ == "__main__":
    main()